WebShop/config/routes.rb
Rails.application.routes.draw do
  resources :news

  get 'search/search'

  resources :news

  resources :article_to_tags

  resources :menu_to_tags

  resources :bill_entries

  resources :bills

  resources :shopping_cart_entries

  resources :menus

  resources :article_structures

  resources :articles

  resources :tags

  resources :users

  get 'shoppingcard' => 'shopping_cart_entries#index'
  get 'create_test_data' => 'application#create_tests'
  get 'home' => 'news#index'
  root 'news#index'

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'search' => 'articles#search'
  get 'by_menu' => 'articles#by_menu'
  
  post 'add_to_shopping_card' => 'articles#add_to_shopping_card'
  post 'buy' => 'shopping_cart_entries#buy'
  get 'associations' => 'articles#association_analysis'
  
  get 'test_area_1' => 'application#test_area_1'
  get 'test_area_2' => 'application#test_area_2'
  get 'legal_information' => 'application#legal_information'
  get 'disclaimer' => 'application#disclaimer'
  get 'privacy_policy' => 'application#privacy_policy'

  get 'notyetimplemented' => 'static_pages#notyetimpemented'

end

WebShop/app/models/shopping_cart_entry.rb
class ShoppingCartEntry < ActiveRecord::Base
  self.primary_keys = :user_id, :article_id
  
  validates_presence_of :amount
  validates_numericality_of :amount, greater_than: 0
  validates_presence_of :user_id
  validates_presence_of :article_id
  
  belongs_to :user
  belongs_to :article
end

WebShop/app/controllers/shopping_cart_entries_controller.rb
class ShoppingCartEntriesController < ApplicationController
  before_action :set_shopping_cart_entry, only: [:show, :edit, :update, :destroy]

  # GET /shopping_cart_entries
  # GET /shopping_cart_entries.json
  def index
    @shopping_cart_entries = ShoppingCartEntry.where(user: current_user)
  end

  def buy
    my_bill = Bill.new(user: current_user)
    my_bill.save
    @shopping_cart_entries = ShoppingCartEntry.where(user: current_user)
    @shopping_cart_entries.each do |entry|
      BillEntry.new(bill: my_bill, article: entry.article, amount: entry.amount).save
      entry.destroy
    end

    redirect_to shoppingcard_path
  end
  # # GET /shopping_cart_entries/1
  # # GET /shopping_cart_entries/1.json
  # def show
  # end
  #
  # GET /shopping_cart_entries/new
  def new
    @shopping_cart_entry = ShoppingCartEntry.new
  end

  # GET /shopping_cart_entries/1/edit
  # def edit
  # end
  #
  # # POST /shopping_cart_entries
  # # POST /shopping_cart_entries.json
  def create
    @shopping_cart_entry = ShoppingCartEntry.new(shopping_cart_entry_params)

    respond_to do |format|
      if @shopping_cart_entry.save
        format.html { redirect_to @shopping_cart_entry, notice: 'Shopping cart entry was successfully created.' }
        format.json { render :show, status: :created, location: @shopping_cart_entry }
      else
        format.html { render :new }
        format.json { render json: @shopping_cart_entry.errors, status: :unprocessable_entity }
      end
    end
  end
  #
  # PATCH/PUT /shopping_cart_entries/1
  # PATCH/PUT /shopping_cart_entries/1.json
  def update
    respond_to do |format|
      if @shopping_cart_entry.update(shopping_cart_entry_params)
        format.html { redirect_to shoppingcard_path, notice: 'Shopping cart entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @shopping_cart_entry }
      else
        format.html { render :edit }
        format.json { render json: @shopping_cart_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shopping_cart_entries/1
  # DELETE /shopping_cart_entries/1.json
  def destroy
    @shopping_cart_entry.destroy
    respond_to do |format|
      format.html { redirect_to shopping_cart_entries_url, notice: 'Shopping cart entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shopping_cart_entry
      @shopping_cart_entry = ShoppingCartEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shopping_cart_entry_params
      params.require(:shopping_cart_entry).permit(:amount)
    end
end

WebShop/app/helpers/shopping_cart_entries_helper.rb
module ShoppingCartEntriesHelper
end

WebShop/app/views/shopping_cart_entries/_form.html.erb
<div class="post">
<%= form_for(@shopping_cart_entry) do |f| %>
  <% if @shopping_cart_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shopping_cart_entry.errors.count, "error") %> prohibited this shopping_cart_entry from being saved:</h2>

      <ul>
      <% @shopping_cart_entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

WebShop/app/views/shopping_cart_entries/edit.html.erb
<div class="post">
<h1>Editing shopping_cart_entry</h1>

<%= render 'form' %>

<%= link_to 'Anzeigen', @shopping_cart_entry %> |
<%= link_to 'Zurück', shopping_cart_entries_path %>
</div>

WebShop/app/views/shopping_cart_entries/index.html.erb
<div class="post">
    <h1>Warenkorb</h1>
    <br/><br/>
    <% if !@shopping_cart_entries.empty? %>
        <% all_price = 0.0 %>
        <% @shopping_cart_entries.each_with_index do |shopping_cart_entry, index| %>
            <% article = shopping_cart_entry.article %>
    
            <%= form_for(shopping_cart_entry) do |f| %>
                <% if shopping_cart_entry.errors.any? %>
                    <div id="error_explanation">
                        <h2><%= pluralize(shopping_cart_entry.errors.count, "error") %> prohibited this shopping_cart_entry from being saved:</h2>
                        <ul>
                            <% shopping_cart_entry.errors.full_messages.each do |message| %>
                                <li><%= message %></li>
                            <% end %>
                        </ul>
                    </div>
                <% end %>

                <% all_price += article.price * shopping_cart_entry.amount%>
                <p style="min-height: 150px;">
                    <span style="margin-right: 30px; float: left; width: 150px; text-align: center;"><%= image_tag article.photo.url(:small) %></span>
                    <%= link_to article.name, article %><br/>
                    <strong>Einzelpreis:</strong> <%= float_to_euro_string(article.price) %><br />
                    <strong>Anzahl: </strong><%= f.number_field :amount %> <%= f.submit "Ändern"%> <br />
                    <strong>Gesamtpreis:</strong> <%= float_to_euro_string(article.price * shopping_cart_entry.amount) %><br />

                    <%= link_to 'Entfernen', shopping_cart_entry, method: :delete, data: { confirm: 'Sind Sie sicher?' } %>
                </p>
                <%= viewtag_seperator %>
            <% end %>
        <% end %>
        <%= form_tag(buy_path , method: "post") do %>
            <%= submit_tag("Kaufen für " + float_to_euro_string(all_price)) %>
        <% end %>
    <% else %>
        Keine Artikel vorhanden
    <% end %>
</div>

WebShop/app/views/shopping_cart_entries/new.html.erb
<div class="post">
<h1>New shopping_cart_entry</h1>

<%= render 'form' %>

<%= link_to 'Zurück', shopping_cart_entries_path %>
</div>

WebShop/app/views/shopping_cart_entries/show.html.erb
<div class="post">
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @shopping_cart_entry.amount %>
</p>

<%= link_to 'Bearbeiten', edit_shopping_cart_entry_path(@shopping_cart_entry) %> |
<%= link_to 'Zurück', shopping_cart_entries_path %>
</div>