WebShop/config/routes.rb
Rails.application.routes.draw do
  resources :news

  get 'search/search'

  resources :news

  resources :article_to_tags

  resources :menu_to_tags

  resources :bill_entries

  resources :bills

  resources :shopping_cart_entries

  resources :menus

  resources :article_structures

  resources :articles

  resources :tags

  resources :users

  get 'shoppingcard' => 'shopping_cart_entries#index'
  get 'create_test_data' => 'application#create_tests'
  get 'home' => 'news#index'
  root 'news#index'

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'search' => 'articles#search'
  get 'by_menu' => 'articles#by_menu'
  
  post 'add_to_shopping_card' => 'articles#add_to_shopping_card'
  post 'buy' => 'shopping_cart_entries#buy'
  get 'associations' => 'articles#association_analysis'
  
  get 'test_area_1' => 'application#test_area_1'
  get 'test_area_2' => 'application#test_area_2'
  get 'legal_information' => 'application#legal_information'
  get 'disclaimer' => 'application#disclaimer'
  get 'privacy_policy' => 'application#privacy_policy'

  get 'notyetimplemented' => 'static_pages#notyetimpemented'

end

WebShop/app/models/article.rb
require 'paperclip/media_type_spoof_detector'
module Paperclip
  class MediaTypeSpoofDetector
    def spoofed?
      false
    end
  end
end

class Article < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :price
  validates_numericality_of :price, greater_than_or_equal_to: 0
  
  has_many :shopping_cart_entries
  has_many :users, :through => :shopping_cart_entries
  has_many :article_to_tags
  has_many :tags, :through => :article_to_tags
  
  has_many :article_structure_to, :foreign_key => 'upper_part_id', :class_name => 'ArticleStructure'
  has_many :article_structure_from, :foreign_key => 'lower_part_id', :class_name => 'ArticleStructure'
  
  has_attached_file :photo, :styles => { :small => "150x150>" },
                  :url  => "/assets/articles/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/articles/:id/:style/:basename.:extension"

  #validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
end

WebShop/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  Paperclip.options[:command_path] = 'C:\Program Files\ImageMagick-6.8.9-Q16'
  
  def association_analysis
    render template: 'articles/associations'
  end

  def add_to_shopping_card
    article_id = params[:article_id].to_i
    amount = params[:amount].to_i
    if(!current_user.nil?)
      add_to_shopping_card_helper(article_id,amount)
    else
      session[:not_insert_shopping_card_entry] = [article_id,amount]
      redirect_to login_path
    end
    #render text: params.to_s
  end

  def by_menu
    set_menu_id(params[:menu_id])
    #flash[:notice] = Menu.find(get_menu_id).all_tags.inject(""){|accu,obj| accu = accu + obj.name.to_s + ", "; accu}
    #@articles = Menu.find(get_menu_id).all_sub_tags.inject(Set.new) { |accu, obj| accu + obj.articles }
    top_tags = Menu.find(get_menu_id).all_top_tags
    if !top_tags.empty?
      @articles = top_tags.inject(top_tags.first.articles.to_set) { |accu, obj| obj.articles.to_set & accu }
    else
      @articles = Article.all
    end
    render template: 'articles/index'
  end
  
  def search
    searchqueries = params[:q].split(' ')
    searchpattern = searchqueries.map { |obj| "(name like '%#{obj}%' OR description like '%#{obj}%')"}.join(" AND ")
    @articles = Article.where(searchpattern)
    render template: 'articles/index'
  end

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.save
    @article.tag_ids = params[:article][:tag_ids].nil? or params[:article][:tag_ids].empty? ? nil : params[:article][:tag_ids].map { |obj| obj.to_i}
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    @article = Article.find(params[:id])
    @article.tag_ids = params[:article][:tag_ids].nil? or params[:article][:tag_ids].empty? ? nil : params[:article][:tag_ids].map { |obj| obj.to_i}
    @article.save
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    if (@article.deleted_at.nil?)
      @article.deleted_at = Time.zone.now
      @article.save

      respond_to do |format|
        format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to articles_url, notice: 'WARNING: Article was already destroyed!' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:name, :description, :price, :deleted_at, :photo, :tag_ids)
    end

end

WebShop/app/helpers/articles_helper.rb
module ArticlesHelper
  # Returns primary requirements analysis for passed month data in following order:
  #   1. first days of previous months
  #   2. actual sales of previous months
  #   3. target sales of previous month
  #   4. result of exponential smoothing
  #   5. result of moving average
  # get_primary_requirements_analysis_data ::= (Article, Date, Float) -> (Array[Date, Date, Date], Array[Int, Int, Int], Float, Float, Float) ::
  def get_primary_requirements_analysis_data(article, first_day, exponential_smoothing_factor)
    previous_month_count = 3
    previous_months = (1..previous_month_count).map{|index| first_day - index.month}.reverse
    
    actual_sales_of_previous_months = previous_months.map{|month|
      get_buyed_amount_in_month(article, month)
    }
    
    moving_average =
      1.0 * actual_sales_of_previous_months.reduce(:+) / previous_month_count
    
    target_sales_of_previous_month = moving_average
    
    exponential_smoothing =
      1.0 * target_sales_of_previous_month +
      exponential_smoothing_factor *
      (actual_sales_of_previous_months[-1] - target_sales_of_previous_month)
    
    return [previous_months, actual_sales_of_previous_months, target_sales_of_previous_month, exponential_smoothing, moving_average]
  end
  
  # caching
  @@cached_articles = {}
  @@cached_bills = {}
  
  def get_cached_article(article)
    @@cached_articles[article.id]
  end
  
  def get_cached_bill(bill)
    @@cached_bills[bill.id]
  end
  
  def cache_articles_and_bills(force)
    if (@@cached_articles.empty? || force)
      @@cached_articles = {}
      @@cached_bills = {}
      
      Article.all.each{|item| @@cached_articles[item.id] = CachedArticle.new(item.id, item.name, "<a href=\"http://127.0.0.1:3000/articles/#{item.id}\">LINK_DESCRIPTION</a>")}
      Bill.all.each{|item| @@cached_bills[item.id] = CachedBill.new(item.id, item.user_id)}
      BillEntry.all.each{|item| @@cached_bills[item.bill_id].add_entry(CachedBillEntry.new(@@cached_bills[item.bill_id], @@cached_articles[item.article_id], item.amount))}
    end
  end
  
  # association analysis
  def get_bill_count_all
    return @@cached_bills.size
  end
  
  def get_bills(articles)
    article_bills = articles.map{|article|
      @@cached_bills.values.select{|bill|
        bill.entry_data.any?{|entry|
          entry.article_data == article
        }
      }
    }
    
    result = article_bills.reduce(:&)
    (result.nil?) ? ([]) : (result.to_a)
  end
  
  def get_bill_count(articles)
    return get_bills(articles).size
  end
  
  def get_support(articles)
    bc_all = get_bill_count_all
    bc_articles = get_bill_count(articles)
    
    support = (bc_all != 0) ? (100.0 * bc_articles / bc_all) : (0.0)
    
    return support
  end
  
  def get_article_sets(min_support)
    articles = @@cached_articles.values.reject{|article| get_support([article]) < min_support}

    # Generate sets with one article
    results = articles.map{|article| [article]}

    # Generate sets with at least two articles
    results.each{|result|
      articles.each{|article|
        if (!result.include?(article))
          new_result = (result | [article]).to_set

          if (!results.include?(new_result) && get_support(new_result) >= min_support)
            results.push(new_result)
          end
        end
      }
    }

    return results
  end
  
  def get_partitions(set)
    yield [] if set.empty?
    (0 ... 2 ** set.size / 2).each do |i|
      parts = [[], []]
      set.each do |item|
        parts[i & 1] << item
        i >>= 1
      end
      get_partitions(parts[1]) do |b|
        result = [parts[0]] + b
        result = result.reject do |e|
          e.empty?
        end
        yield result
      end
    end
  end
  
  def association_analysis_data(min_support, min_confidence)
    article_sets = get_article_sets(min_support)
    bc_all = get_bill_count_all

    result = []
    article_sets.each{|item|
      get_partitions(item.to_set){|partition|
        if (partition.size == 2)
          left = partition[0]
          right = partition[1]

          bc_left = get_bill_count(left)
          bc_right = get_bill_count(right)

          bc_both = get_bill_count(left | right)
          support = (bc_all != 0) ? (100.0 * bc_both / bc_all) : (0.0)

          left_to_right_confidence = (bc_left != 0) ? (100.0 * bc_both / bc_left) : (0.0)
          if (left_to_right_confidence >= min_confidence)
            result.push([left, right, bc_left, bc_right, bc_both, left_to_right_confidence, support])
          end

          right_to_left_confidence = (bc_right != 0) ? (100.0 * bc_both / bc_right) : (0.0)
          if (right_to_left_confidence >= min_confidence)
            result.push([right, left, bc_right, bc_left, bc_both, right_to_left_confidence, support])
          end
        end
      }
    }
    
    # Sort by articles
    result.sort!

    # Sort by confidence and support
    result.sort!{|a, b|
        temp = b[5] <=> a[5]
        (temp == 0) ? (b[6] <=> a[6]) : temp}
    return result
  end
  
  def association_analysis_data_of(left, min_support, min_confidence)
    bc_all = get_bill_count_all
    
    left = [left]
    bc_left = get_bill_count(left)

    result = []
    @@cached_articles.values.each{|article|
      right = [article]
      bc_right = get_bill_count(right)

      bc_both = get_bill_count(left | right)
      support = (bc_all != 0) ? (100.0 * bc_both / bc_all) : (0.0)
      if (support >= min_support)
        left_to_right_confidence = (bc_left != 0) ? (100.0 * bc_both / bc_left) : (0.0)
        if (left_to_right_confidence >= min_confidence)
          result.push([left, right, bc_left, bc_right, bc_both, left_to_right_confidence, support])
        end
      end
    }
    
    # Sort by articles
    result.sort!

    # Sort by confidence and support
    result.sort!{|a, b|
        temp = b[5] <=> a[5]
        (temp == 0) ? (b[6] <=> a[6]) : temp}
    return result
  end
  
  # shopping card
  def add_to_shopping_card_helper(article_id, amount)
    article = Article.find(article_id)
    entry = ShoppingCartEntry.where(user: current_user, article: article)
    if(entry.empty?)
      ShoppingCartEntry.new(user: current_user, amount: amount, article: article).save
    else
      entry.first.amount += amount
      entry.first.save
    end
    session[:not_insert_shopping_card_entry] = nil
    redirect_to(article)
  end
end

class CachedBill
  def initialize(id, user_id)
    @id = id
    @user_id = user_id
    @entry_data = []
  end
  
  attr_reader :id
  attr_reader :user_id
  attr_reader :entry_data
  
  def add_entry(entry_data)
    @entry_data.push(entry_data)
  end
  
  def to_s
    return "B" + @id.to_s
  end
  
  def <=>(o)
    return self.id <=> o.id
  end
end

class CachedBillEntry
  def initialize(bill_data, article_data, amount)
    @bill_data = bill_data
    @article_data = article_data
    @amount = amount
  end
  
  attr_reader :bill_data
  attr_reader :article_data
  attr_reader :amount
end

class CachedArticle
  def initialize(id, name, link_to)
    @id = id
    @name = name
    @link_to = link_to
  end
  
  attr_reader :id
  attr_reader :name
  
  def link_to(description)
    return @link_to.sub("LINK_DESCRIPTION", description).html_safe
  end
  
  def to_s
    return "A" + @id.to_s
  end
  
  def <=>(o)
    return self.id <=> o.id
  end
end

WebShop/app/views/articles/_form.html.erb
<div class="post">
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <% Tag.all.each do |entry| %>
        <label>
          <%= check_box_tag "article[tag_ids][]", entry.id, @article.tags.include?(entry) %>
          <%= entry.name %>
        </label><br />
    <% end %>
  </div>
  <div class="field">
    <%= f.file_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

WebShop/app/views/articles/edit.html.erb
<div class="post">
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Anzeigen', @article %> |
<%= link_to 'Zurück', articles_path %>
</div>

WebShop/app/views/articles/index.html.erb
<h1>Artikel</h1>
<br/><br/>

<div class="post">
    <% selected_articles = (admin_user?) ? (@articles) : (@articles.select{|item| item.deleted_at.nil?}) %> 
    <% selected_articles.each_with_index do |article, index| %>
        <p style="min-height: 150px;">
            <span style="margin-right: 30px; float: left; width: 150px; text-align: center;"><%= image_tag article.photo.url(:small) %></span>
            <%= link_to article.name, article %><br/>
            <strong>Preis:</strong>
            <%= float_to_euro_string(article.price) %>
            
            <% if (admin_user?) %>
                <br/>
                <%= link_to 'Bearbeiten', edit_article_path(article) %> | 
                <%= link_to 'Löschen', article, method: :delete, data: { confirm: 'Sind Sie sicher?' } %>
            <% end %>
        </p>
        <% if ((index != selected_articles.size - 1) || admin_user?) %>
            <%= viewtag_seperator %>
        <% end %>
    <% end %>
    
    <% if (admin_user?) %>
        <p>
            <%= viewtag_admin %><br/>
            <%= link_to 'Neuer Artikel', new_article_path %>
        </p>
    <% end %>
</div>

WebShop/app/views/articles/new.html.erb
<div class="post">
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Zurück', articles_path %>
</div>

WebShop/app/views/articles/show.html.erb
<script type="text/javascript">
  function validateForm() {
      var result;
      var val_exponential_smoothing_factor = document.getElementById('exponential_smoothing_factor').value;
      var val_target_date = document.getElementById('target_date').value;
      
      val_exponential_smoothing_factor = val_exponential_smoothing_factor.replace(",", "."); 
      result = (!isNaN(val_exponential_smoothing_factor) && val_exponential_smoothing_factor.toString().indexOf('.') != -1) && (val_exponential_smoothing_factor >= 0.1) && (val_exponential_smoothing_factor <= 0.3);
      if (!result) {
        alert("Glättungsfaktor muss zwischen 0,10 und 0,30 liegen!");
        return false;
      }
      
      result = (val_target_date).match(/^((0\d)|(10)|(11)|(12))\.\d\d\d\d$/);
      if (!result) {
        alert("Monat muss im Format MM.JJJJ angegeben werden (z.B. 11.2014)!");
        return false;
      }
      
      document.getElementById('exponential_smoothing_factor').value = document.getElementById('exponential_smoothing_factor').value.replace(".", ",");
      return true;
  }
</script>

<%
  def product_structure_output(article, parent_amount, accu)
    lower_parts = ArticleStructure.where(upper_part: article)
    if (!lower_parts.empty?)
      accu.push("<ul>")
    end

    lower_parts.each {|item|
      count = parent_amount * item.amount
      accu.push("<li style=\"margin-bottom: 10px;\">" + count.to_s + "x " + link_to(item.lower_part.name, item.lower_part) + "</li>")
      product_structure_output(item.lower_part, count, accu)
    }

    if (!lower_parts.empty?)
      accu.push("</ul>")
    end

    return accu
  end

  def best_list_output
    result = []
    
    menus_data = get_menus_of_article(@article)
    menus_data.each{|item| place, size = get_place_at_menu(@article, item)
      result.push("Platz #{place} (von #{size}) in " + 
        link_to(item.name, by_menu_path(:menu_id => item.id)).to_s)}

    place, size = get_place(@article)
    result.push("Platz #{place} (von #{size}) in allen Artikeln")
    
    return result.flat_map{|item| [item, "<br/>"]}[0...-1]
  end
%>

<div class="post">
    <table style="width: 100%;">
        <tr>
            <td><h1><%= @article.name %></h1></td>
            <td width="180px" height="150px" align="right"><%= image_tag @article.photo.url(:small) %></td>
        </tr>
    </table>

    <div class="post" style="margin-top: 30px;">
        <p>
          <strong>Produktbezeichnung:<br/></strong>
          <%= @article.name %>
        </p>

        <p>
          <strong>Produktbeschreibung:<br/></strong>
          <%= @article.description %>
        </p>

        <p>
          <strong>Preis:</strong>
          <%= float_to_euro_string(@article.price) %>
        </p>
        
        <%= viewtag_seperator_without_space_bottom %>
        <p>
            <div style="width: 596px;">
                <div style="min-height: 53px; width: 375px; padding-top: 30px; padding-bottom: 30px; margin-top: -13px; margin-bottom: -14px; border-right: solid 1px #d3d7d9; float: left;">
                    <strong>Bestseller-Rang:</strong><br/>
                    <% best_list_output.each{|item| %>
                        <%= item.html_safe %>
                    <% } %>
                </div>
                <div style="width: 178px; padding-top: 17px; padding-bottom: 16px; float: right; text-align: center;">
                    <%= form_tag(add_to_shopping_card_path, method: "post") do %>
                        <div style="margin-bottom: 10px">
                            Menge:&nbsp;&nbsp;&nbsp;
                            <%= select_tag :amount, options_for_select((1..10).step(1)) %>
                        </div>
                        <div style="display: none;">
                            <%= text_field_tag :article_id, @article.id %>
                        </div>
                        <%= submit_tag("Zum Warenkorb hinzufügen") %>
                    <% end %>
                </div>
                <div style="clear: both;"></div>
            </div>
        </p>
        
        <%= viewtag_seperator_without_space_top %>
        <% 
            cache_articles_and_bills(true)
            min_support = 0.0
            min_confidence = 0.0
            association_data = association_analysis_data_of(get_cached_article(@article), min_support, min_confidence)
        %>
        
        <% if (admin_user?) %>
            <strong>Assoziationsanalyse:</strong><br/>
            <% bill_count_self = get_bill_count([get_cached_article(@article)]) %>
            <% if (bill_count_self > 0) %>
                Insgesamt wurden <%= get_bill_count_all %> Verkaufstransaktionen getätigt.<br/>
                Der aktuelle Artikel kommt in <%= bill_count_self %> dieser Verkaufstransaktionen vor.<br/>
                Folgende Artikel kamen ebenfalls in diesen Verkaufstransaktionen vor:
                <br/><br/>
                <table border="1px" bordercolor="#d3d7d9" frame="void" rules="rows" style="margin-left: 20px; width: 580px; border: solid 1px #d3d7d9">
                    <tr>
                        <td style="padding: 5px;"><strong>Artikelbezeichnung</strong></td>
                        <td style="text-align: center; width: 65px; padding: 5px;"><strong>Konfidenz</strong></td>
                        <td style="text-align: center; width: 60px; padding: 5px;"><strong>Support</strong></td>
                    </tr>
                    <% association_data.each{|data| %>
                        <tr>
                            <td style="padding: 5px;">
                                <%= data[1][0].link_to("#{(data[1][0].name.size > 55) ? (data[1][0].name[0..55].to_s + "...") : (data[1][0].name)}") %>, 
                            </td>
                            <td style="text-align: center; padding: 5px;"><%= format("%.2f", data[5]).to_s.sub(".", ",") %> %</td>
                            <td style="text-align: center; padding: 5px;"><%= format("%.2f", data[6]).to_s.sub(".", ",") %> %</td>
                        </tr>
                    <% } %>
                </table>
            <% else %>
                Insgesamt wurden <%= get_bill_count_all %> Verkaufstransaktionen getätigt.<br/>
                Der aktuelle Artikel kommt in keiner dieser Verkaufstransaktionen vor.
            <% end %>
        <% else %>
            <% association_data = association_data[0..3] %>
            <strong>Kunden, die diesen Artikel gekauft haben, kauften auch:</strong>
            <div style="margin-top: 20px; margin-left: 1px;">
                <div style="width: 146px; display: inline-block; vertical-align: top;">
                    <% association_data.each{|left, right, bc_left, bc_right, bc_both, left2right_confidence, support| %>
                        <div style="width: 125px;">
                            <% #image_tag right[0].photo.url(:small), size: "125" %>
                            <%= right[0].link_to((right[0].name.size > 55) ? (right[0].name[0..55].to_s + "...") : right[0].name) %>
                        </div>
                    <% } %>
                </div>
            </div>
        <% end %>
            
        <% if (admin_user?) %>
            <%= viewtag_seperator %>
            <p>
                <strong>Primärbedarfsanalyse</strong><br/>
                <%
                  # default values
                  target_date = Date.current
                  exponential_smoothing_factor = 0.1
                  
                  # get parameters if passed
                  if (request.GET.include? "target_date")
                    target_date = get_date_from_german_month_ordinal(params[:target_date].to_s)
                  end
                  if (request.GET.include? "exponential_smoothing_factor")
                    exponential_smoothing_factor = params[:exponential_smoothing_factor].to_s.sub(",", ".").to_f
                  end

                  # correct values of parameters
                  target_date = get_date_from_german_month_ordinal(get_german_month_from_date_ordinal(target_date).to_s)
                  exponential_smoothing_factor = exponential_smoothing_factor.round(2)

                  # generate analysis data
                  analysis_data = get_primary_requirements_analysis_data(@article, target_date, exponential_smoothing_factor)
                %>
                
                <%= form_tag('' , method: "get") do %>
                    <table style="margin-left: 20px; margin-top: 6px; margin-bottom: 20px;">
                        <tr>
                            <td><strong><em>Parameter für die Berechnung:</em></strong>&nbsp;&nbsp;&nbsp;</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>Glättungsfaktor für die exponentielle Glättung:</td>
                            <td style="text-align: center"><%= text_field_tag :exponential_smoothing_factor, format("%.2f", exponential_smoothing_factor).to_s.sub(".", ","), size: 7 %></td>
                        </tr>
                        <tr>
                            <td>Schätzung für den Monat:</td>
                            <td style="text-align: center"><%= text_field_tag :target_date, get_german_month_from_date_ordinal(target_date).to_s, size: 7 %></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td style="text-align: center"><%= submit_tag("Berechnen", :onclick => "return validateForm();") %></td>
                        </tr>
                    </table>
                <% end %>
            
                <span style="margin-left: 20px">
                    <strong><em>Ergebnisse der Berechnung:</em></strong>
                </span>
            
                <br/>
                
                <table border="1px" bordercolor="#d3d7d9" frame="void" rules="rows" style="margin-left: 20px; margin-top: 6px; width: 580px; border: solid 1px #d3d7d9">",
                    <tr>
                        <td style="padding: 5px;">Ist-Absätze für die vorhergenden Monate:</td>
                        <td style="text-align: center; width: 100px; padding: 5px;"></td>
                    </tr>
                    <tr>
                        <td style="padding: 5px;">&nbsp;&nbsp;&nbsp;<%= get_german_month_from_date(analysis_data[0][0]) %>:</td>
                        <td style="text-align: center; padding: 5px;"><%= analysis_data[1][0] %>,0 Stück</td>
                    </tr>
                    <tr>
                        <td style="padding: 5px;">&nbsp;&nbsp;&nbsp;<%= get_german_month_from_date(analysis_data[0][1]) %>:</td>
                        <td style="text-align: center; padding: 5px;"> <%= analysis_data[1][1] %>,0 Stück</td></tr>
                    <tr>
                        <td style="padding: 5px;">&nbsp;&nbsp;&nbsp;<%= get_german_month_from_date(analysis_data[0][2]) %>:</td>
                        <td style="text-align: center; padding: 5px;"> <%= analysis_data[1][2] %>,0 Stück</td></tr>
                    <tr>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td style="padding: 5px;">Soll-Absatz für den Monat <%= get_german_month_from_date(analysis_data[0][2]) %>:</td>
                        <td style="text-align: center; padding: 5px;"><%= format("%.1f", analysis_data[2]).to_s.sub(".", ",") %> Stück</td></tr>
                    <tr>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td style="padding: 5px;">Glättungsfaktor für die exponentielle Glättung:</td>
                        <td style="text-align: center; padding: 5px;">&alpha; = <%= format("%.2f", exponential_smoothing_factor).to_s.sub(".", ",") %><br/></td>
                    </tr>
                    <tr>
                        <td style="padding: 5px;">Exponentielle Glättung für den Monat <%= get_german_month_from_date(target_date) %>:</td>
                        <td style="text-align: center; padding: 5px;"><%= format("%.1f", analysis_data[3]).to_s.sub(".", ",") %> Stück</td></tr>
                    <tr>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td style="padding: 5px;">Gleitender Durchschnitt für den Monat <%= get_german_month_from_date(target_date) %>:</td>
                        <td style="text-align: center; padding: 5px;"><%= format("%.1f", analysis_data[4]).to_s.sub(".", ",") %> Stück</td>
                    </tr>
                </table>
            </p>
        <% end %>
        
        <% product_structure_output_list = product_structure_output(@article, 1, []) %>
        <% if (!product_structure_output_list.empty?) %>
            <%= viewtag_seperator %>
            <p>
                <strong>Strukturstückliste:</strong><br/>
                <% product_structure_output_list.each {|line| %>
                    <%= line.html_safe %>
                <%} %>
            </p>
        <% end %>

        <% if (admin_user?) %>
            <%= viewtag_seperator %>
            <p>
              <strong>Erstellt am:</strong>
              <%= get_german_date_time_ordinal(@article.created_at.to_datetime) %>
            </p>

            <% if (!@article.deleted_at.nil?) %>
              <p>
                <strong>Gelöscht am:</strong>
                <%= get_german_date_time_ordinal(@article.deleted_at.to_datetime) %>
              </p>
            <% end %>
            
            <p>
              <%= viewtag_admin %><br/>
              <%= link_to 'Bearbeiten', edit_article_path(@article) %> | 
              <%= link_to 'Zurück', articles_path %>
            </p>
        <% end %>    
    </div>
</div>