WebShop/config/routes.rb
Rails.application.routes.draw do
  resources :news

  get 'search/search'

  resources :news

  resources :article_to_tags

  resources :menu_to_tags

  resources :bill_entries

  resources :bills

  resources :shopping_cart_entries

  resources :menus

  resources :article_structures

  resources :articles

  resources :tags

  resources :users

  get 'shoppingcard' => 'shopping_cart_entries#index'
  get 'create_test_data' => 'application#create_tests'
  get 'home' => 'news#index'
  root 'news#index'

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'search' => 'articles#search'
  get 'by_menu' => 'articles#by_menu'
  
  post 'add_to_shopping_card' => 'articles#add_to_shopping_card'
  post 'buy' => 'shopping_cart_entries#buy'
  get 'associations' => 'articles#association_analysis'
  
  get 'test_area_1' => 'application#test_area_1'
  get 'test_area_2' => 'application#test_area_2'
  get 'legal_information' => 'application#legal_information'
  get 'disclaimer' => 'application#disclaimer'
  get 'privacy_policy' => 'application#privacy_policy'

  get 'notyetimplemented' => 'static_pages#notyetimpemented'

end

WebShop/app/views/layouts/_header.html.erb
<div id="banner-wrapper"></div>
<div id="header-wrapper">
  <div id="header" class="container">
    <div id="logo">
      <%= form_tag(search_path , method: "get") do %>
          <%= text_field_tag :q, '', size: 35 %>
          &nbsp;
          <%= submit_tag("Suche") %>
      <% end %>
    </div>
    
    <div id='cssmenu'>
      <ul>
        <li><%= link_to "Home", :root %></li>
        
        <% if logged_in? %>
            <li><%= link_to "Warenkorb", shoppingcard_path %></li>
        <% else %>
            <li><%= link_to "Warenkorb", :login %></li>
        <% end %>
        
        <% if logged_in? %>
          <li>
          <% if admin_user? %>
            <%= link_to "Admin", '#' %>
            <ul>
              <li><%= link_to "Assoziationsanalyse", associations_path %></li>
              <li><%= link_to "Tags bearbeiten", tags_path %></li>
              <li><%= link_to "Benutzer bearbeiten", users_path %></li>
              <li><%= link_to "Menü bearbeiten", menus_path %></li>
            </ul>
          <% end %>
          </li>
          <li>
            <%= link_to current_user.firstname + " " + current_user.lastname , current_user %>
            <ul>
              <li><%= link_to "Edit Profile" , edit_user_path(current_user)%></li>
              <li><%= link_to 'Logout', :logout, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", :signup %></li>
          <li><%= link_to "Login", :login %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

WebShop/app/views/layouts/_menu.erb
<%
    def get_menu(id)
      if id.nil?
        Menu.where("super_menu_id is null")
      else
        Menu.where("super_menu_id = #{id}")
      end
    end
%>
<% def generate_menu(id)
        accu = ""
        include_menu = false
        menus = get_menu(id)
        if !menus.empty?
            menus.each{ |entry|
                accu += "<li class=\"" + (get_menu_id == entry.id ? (include_menu = true; "chosenElement") : "unChosenElement") + "\">" + link_to(entry.name, by_menu_path(:menu_id => entry.id)).to_s + "</li>"
                sub_menus = generate_menu(entry.id)
                include_menu = include_menu || sub_menus[1]
                if not(sub_menus[0].empty?)
                  accu += sub_menus[0]
                end
            }
        end
        if (!accu.empty? and (include_menu or id == get_menu_id)) or id == nil
            accu = "<ul>" + accu + "</ul>"
            [accu, include_menu]
        else
            ["",include_menu]
        end

 end %>

<%= (generate_menu(nil)[0]).to_s.html_safe %>

WebShop/app/views/layouts/_menu.html.erb
<%
    def get_menu(id)
      if id.nil?
        Menu.where("super_menu_id is null")
      else
        Menu.where("super_menu_id = #{id}")
      end
    end
%>
<% def generate_menu(id)
        accu = ""
        include_menu = false
        menus = get_menu(id)
        if !menus.empty?
            menus.each{ |entry|
                accu += "<li class=\"" + (get_menu_id == entry.id ? (include_menu = true; "chosenElement") : "unChosenElement") + "\">" + link_to(entry.name, by_menu_path(:menu_id => entry.id)).to_s + "</li>"
                sub_menus = generate_menu(entry.id)
                include_menu = include_menu || sub_menus[1]
                if not(sub_menus[0].empty?)
                  accu += sub_menus[0]
                end
            }
        end
        if (!accu.empty? and (include_menu or id == get_menu_id)) or id == nil
            accu = "<ul>" + accu + "</ul>"
            [accu, include_menu]
        else
            ["",include_menu]
        end

 end %>

<%= (generate_menu(nil)[0]).to_s.html_safe %>

WebShop/app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by TEMPLATED
http://templated.co
Released for free under the Creative Commons Attribution License

Name       : Monumental 
Description: A two-column, fixed-width design with dark color scheme.
Version    : 1.0
Released   : 20130902

-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>WebShop</title>
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700|Archivo+Narrow:400,700" rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%=
    # Including the header
    # for changing it please change
    # /layouts/_header.html.erb
    render 'layouts/header'
%>

<% 
    no_redirect_to = ["/login", "/logout", "/signin"]
    if (!request.original_url.nil? && no_redirect_to.all? {|item| !request.original_url.include?(item)})
        session[:return_to] = request.original_url
    end
%>
    
<div id="page" class="container">
    <div id="sidebar">
        <%= render 'layouts/menu' %>
    </div>
    <!-- end #sidebar -->
    
    <div id="content">
        <% if !flash.empty? then %>
            <div class="post" style="border: 5px solid #880000;">
                <p id="notice"><%= notice %></p>
            </div>
        <% end %>
        
        <%= yield %>
    </div>
    <!-- end #content -->    
</div>
<div id="footer" class="container">
    <p>&copy; 2014 Torben Haug, Andreas Berks. Alle Rechte vorbehalten.<br/>
      <a href="legal_information"><strong>Impressum</strong></a> | 
      <a href="disclaimer"><strong>Disclaimer</strong></a> | 
      <a href="privacy_policy"><strong>Datenschutzerklärung</strong></a>
    </p>
</div>
    
<%= debug(params) if print_debug %>

<%= piwik_tracking_tag %>
</body>
</html>