WebShop/config/routes.rb
Rails.application.routes.draw do
  resources :news

  get 'search/search'

  resources :news

  resources :article_to_tags

  resources :menu_to_tags

  resources :bill_entries

  resources :bills

  resources :shopping_cart_entries

  resources :menus

  resources :article_structures

  resources :articles

  resources :tags

  resources :users

  get 'shoppingcard' => 'shopping_cart_entries#index'
  get 'create_test_data' => 'application#create_tests'
  get 'home' => 'news#index'
  root 'news#index'

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'search' => 'articles#search'
  get 'by_menu' => 'articles#by_menu'
  
  post 'add_to_shopping_card' => 'articles#add_to_shopping_card'
  post 'buy' => 'shopping_cart_entries#buy'
  get 'associations' => 'articles#association_analysis'
  
  get 'test_area_1' => 'application#test_area_1'
  get 'test_area_2' => 'application#test_area_2'
  get 'legal_information' => 'application#legal_information'
  get 'disclaimer' => 'application#disclaimer'
  get 'privacy_policy' => 'application#privacy_policy'

  get 'notyetimplemented' => 'static_pages#notyetimpemented'

end

WebShop/app/models/article_to_tag.rb
class ArticleToTag < ActiveRecord::Base
  validates_presence_of :article_id
  validates_presence_of :tag_id
  
  belongs_to :article
  belongs_to :tag
end

WebShop/app/controllers/article_to_tags_controller.rb
class ArticleToTagsController < ApplicationController
  before_action :set_article_to_tag, only: [:show, :edit, :update, :destroy]

  # GET /article_to_tags
  # GET /article_to_tags.json
  def index
    @article_to_tags = ArticleToTag.all
  end

  # GET /article_to_tags/1
  # GET /article_to_tags/1.json
  def show
  end

  # GET /article_to_tags/new
  def new
    @article_to_tag = ArticleToTag.new
  end

  # GET /article_to_tags/1/edit
  def edit
  end

  # POST /article_to_tags
  # POST /article_to_tags.json
  def create
    @article_to_tag = ArticleToTag.new(article_to_tag_params)

    respond_to do |format|
      if @article_to_tag.save
        format.html { redirect_to @article_to_tag, notice: 'Article to tag was successfully created.' }
        format.json { render :show, status: :created, location: @article_to_tag }
      else
        format.html { render :new }
        format.json { render json: @article_to_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /article_to_tags/1
  # PATCH/PUT /article_to_tags/1.json
  def update
    respond_to do |format|
      if @article_to_tag.update(article_to_tag_params)
        format.html { redirect_to @article_to_tag, notice: 'Article to tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @article_to_tag }
      else
        format.html { render :edit }
        format.json { render json: @article_to_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /article_to_tags/1
  # DELETE /article_to_tags/1.json
  def destroy
    @article_to_tag.destroy
    respond_to do |format|
      format.html { redirect_to article_to_tags_url, notice: 'Article to tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article_to_tag
      @article_to_tag = ArticleToTag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_to_tag_params
      params[:article_to_tag]
    end
end

WebShop/app/helpers/article_to_tags_helper.rb
module ArticleToTagsHelper
end

WebShop/app/views/article_to_tags/_form.html.erb
<div class="post">
<%= form_for(@article_to_tag) do |f| %>
  <% if @article_to_tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article_to_tag.errors.count, "error") %> prohibited this article_to_tag from being saved:</h2>

      <ul>
      <% @article_to_tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

WebShop/app/views/article_to_tags/edit.html.erb
<div class="post">
<h1>Editing article_to_tag</h1>

<%= render 'form' %>

<%= link_to 'Anzeigen', @article_to_tag %> |
<%= link_to 'Zurück', article_to_tags_path %>
</div>

WebShop/app/views/article_to_tags/index.html.erb
<div class="post">
<h1>Listing article_to_tags</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @article_to_tags.each do |article_to_tag| %>
      <tr>
        <td><%= link_to 'Anzeigen', article_to_tag %></td>
        <td><%= link_to 'Bearbeiten', edit_article_to_tag_path(article_to_tag) %></td>
        <td><%= link_to 'Löschen', article_to_tag, method: :delete, data: { confirm: 'Sind Sie sicher?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article to tag', new_article_to_tag_path %>
</div>

WebShop/app/views/article_to_tags/new.html.erb
<div class="post">
<h1>New article_to_tag</h1>

<%= render 'form' %>

<%= link_to 'Zurück', article_to_tags_path %>
</div>

WebShop/app/views/article_to_tags/show.html.erb
<div class="post">
<p id="notice"><%= notice %></p>

<%= link_to 'Bearbeiten', edit_article_to_tag_path(@article_to_tag) %> |
<%= link_to 'Zurück', article_to_tags_path %>
</div>